services:
  database:
    container_name: employee_database
    image: mongo:8.3-noble
    ports:
      - 27017:27017
    volumes:
      - employee_database:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
    command: ["--auth"]

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - database
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://${DATABASE_USER}:${DATABASE_PASSWORD}@database:27017/?authSource=admin"
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass

volumes:
  employee_database:
